version: '3.5'
  
services:
    crawler:
        image: webrecorder/browsertrix-crawler:0.3.1
        build:
          context: ./

        volumes:
          - ./crawls:/crawls
          - ./tests/fixtures:/fixtures

        cap_add:
          - NET_ADMIN
          - SYS_ADMIN

        shm_size: 1gb
